// clang-format off

#ifndef RJK_DUCK_VIEW_HPP
#define RJK_DUCK_VIEW_HPP

// (No support for formatting reflection currently)
// clang-format off

#ifndef RJK_DUCK_HPP
#define RJK_DUCK_HPP

#include <algorithm>
#include <array>
#include <cassert>
#include <concepts>
#include <meta>

// clang-format off

#ifndef RJK_DUCK_TAGS_HPP
#define RJK_DUCK_TAGS_HPP

// This file was automatically generated by generate_operators.py.

#ifndef RJK_DO_UNARY_OP_HPP
#define RJK_DO_UNARY_OP_HPP

#include <meta>

namespace rjk {

template <std::meta::operators Op, typename Operand>
constexpr decltype(auto) do_unary_op(Operand&& operand) {
using enum std::meta::operators;
    if constexpr (Op == op_tilde) return ~std::forward<Operand>(operand);
    if constexpr (Op == op_exclamation) return !std::forward<Operand>(operand);
    if constexpr (Op == op_plus_plus) return ++std::forward<Operand>(operand);
    if constexpr (Op == op_minus_minus) return --std::forward<Operand>(operand);
    if constexpr (Op == op_plus) return +std::forward<Operand>(operand);
    if constexpr (Op == op_minus) return -std::forward<Operand>(operand);
    if constexpr (Op == op_star) return *std::forward<Operand>(operand);
    if constexpr (Op == op_ampersand) return &std::forward<Operand>(operand);
    if constexpr (Op == op_arrow) return std::forward<Operand>(operand).operator->();
    throw std::logic_error{"invalid operator"};
}
}

#endif
// This file was automatically generated by generate_operators.py.

#ifndef RJK_DO_BINARY_OP_HPP
#define RJK_DO_BINARY_OP_HPP

#include <meta>

namespace rjk {

template <std::meta::operators Op, typename Lhs, typename Rhs>
constexpr decltype(auto) do_binary_op(Lhs&& lhs, Rhs&& rhs) {
using enum std::meta::operators;
    if constexpr (Op == op_plus) return std::forward<Lhs>(lhs) + std::forward<Rhs>(rhs);
    if constexpr (Op == op_minus) return std::forward<Lhs>(lhs) - std::forward<Rhs>(rhs);
    if constexpr (Op == op_star) return std::forward<Lhs>(lhs) * std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand) return std::forward<Lhs>(lhs) & std::forward<Rhs>(rhs);
    if constexpr (Op == op_slash) return std::forward<Lhs>(lhs) / std::forward<Rhs>(rhs);
    if constexpr (Op == op_percent) return std::forward<Lhs>(lhs) % std::forward<Rhs>(rhs);
    if constexpr (Op == op_caret) return std::forward<Lhs>(lhs) ^ std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe) return std::forward<Lhs>(lhs) | std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_less) return std::forward<Lhs>(lhs) << std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_greater) return std::forward<Lhs>(lhs) >> std::forward<Rhs>(rhs);
    if constexpr (Op == op_comma) return std::forward<Lhs>(lhs) , std::forward<Rhs>(rhs);
    if constexpr (Op == op_plus_equals) return std::forward<Lhs>(lhs) += std::forward<Rhs>(rhs);
    if constexpr (Op == op_minus_equals) return std::forward<Lhs>(lhs) -= std::forward<Rhs>(rhs);
    if constexpr (Op == op_star_equals) return std::forward<Lhs>(lhs) *= std::forward<Rhs>(rhs);
    if constexpr (Op == op_slash_equals) return std::forward<Lhs>(lhs) /= std::forward<Rhs>(rhs);
    if constexpr (Op == op_percent_equals) return std::forward<Lhs>(lhs) %= std::forward<Rhs>(rhs);
    if constexpr (Op == op_caret_equals) return std::forward<Lhs>(lhs) ^= std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand_equals) return std::forward<Lhs>(lhs) &= std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe_equals) return std::forward<Lhs>(lhs) |= std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_less_equals) return std::forward<Lhs>(lhs) <<= std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_greater_equals) return std::forward<Lhs>(lhs) >>= std::forward<Rhs>(rhs);
    if constexpr (Op == op_equals_equals) return std::forward<Lhs>(lhs) == std::forward<Rhs>(rhs);
    if constexpr (Op == op_exclamation_equals) return std::forward<Lhs>(lhs) != std::forward<Rhs>(rhs);
    if constexpr (Op == op_less) return std::forward<Lhs>(lhs) < std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater) return std::forward<Lhs>(lhs) > std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_equals) return std::forward<Lhs>(lhs) <= std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_equals) return std::forward<Lhs>(lhs) >= std::forward<Rhs>(rhs);
    if constexpr (Op == op_spaceship) return std::forward<Lhs>(lhs) <=> std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand_ampersand) return std::forward<Lhs>(lhs) && std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe_pipe) return std::forward<Lhs>(lhs) || std::forward<Rhs>(rhs);
    if constexpr(Op == op_plus_plus) return std::forward<Lhs>(lhs)++;
    if constexpr(Op == op_minus_minus) return std::forward<Lhs>(lhs)--;
    if constexpr(Op == op_arrow_star) return std::forward<Lhs>(lhs).operator->*(std::forward<Rhs>(rhs));
    throw std::logic_error{"invalid operator"};
}
}

#endif
// clang-format off

#ifndef RJK_FIXED_STRING_HPP
#define RJK_FIXED_STRING_HPP

#include <meta>

namespace rjk {

// Compile-time string primitive. We need this to be able to pass
// strings as template arguments.
struct fixed_string {
    consteval fixed_string() = default;

    template <std::size_t N>
    consteval fixed_string(const char (&str)[N]) {
        m_data = std::define_static_string(str);
        m_length = N - 1;
    }

    consteval explicit fixed_string(std::string_view str) {
        m_data = std::define_static_string(str);
        m_length = str.size();
    }

    consteval bool operator==(const fixed_string&) const = default;

    consteval auto operator+(const fixed_string& other) const {
        std::string result_str{m_data};
        result_str += other.m_data;

        return fixed_string{std::string_view{result_str}};
    }

    consteval const char* data() const { return m_data; }
    consteval std::size_t size() const { return m_length; }

    consteval explicit operator std::string_view() const {
        return {m_data, m_length};
    }

    const char* m_data{};
    std::size_t m_length{};
};
}

#endif
// clang-format off

#ifndef RJK_FLAG_ENUM_HPP
#define RJK_FLAG_ENUM_HPP

#include <utility>

namespace rjk::detail {

// Use in an attribute like [[=detail::flag_enum]] to mark that an enumeration
// type consists only of flags.
constexpr inline struct{} flag_enum{};

consteval bool has_annotation(std::meta::info obj, std::meta::info annotation) {
    return std::ranges::any_of(annotations_of(obj),
        [annotation](auto a) { return type_of(a) == type_of(annotation); });
}

template <typename T>
concept is_flag_enum = std::is_enum_v<T> && requires { T::none == static_cast<T>(0); }
    && has_annotation(^^T, ^^flag_enum);

// Now every type with the flag_enum attribute gets the following operators for free.

template <is_flag_enum EnumType>
constexpr EnumType operator|(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) | std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator|=(EnumType& lhs, EnumType rhs) {
    lhs = lhs | rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator&(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) & std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator&=(EnumType& lhs, EnumType rhs) {
    lhs = lhs & rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator~(EnumType operand) {
    return static_cast<EnumType>(~std::to_underlying(operand));
}
}

#endif
// clang-format off

#ifndef RJK_FN_TRAITS_HPP
#define RJK_FN_TRAITS_HPP

#include <type_traits>
#include <meta>
#include <ranges>

namespace rjk::detail {

// Allows easy translation between concepts and meta-functions.
template <typename T, auto Func>
concept evaluate = Func(^^T);

template <typename Ret, typename... Args>
using make_func_t = Ret(Args...);

template <std::meta::info Ret, std::meta::info... Args>
using make_func_meta = make_func_t<typename [:Ret:], typename [:Args:]...>;

// Creates a function type with the provided return type and arguments.
template <std::meta::reflection_range R = std::initializer_list<std::meta::info>>
consteval std::meta::info make_func(std::meta::info ret, R&& args) {
    std::vector template_args{ret};
    template_args.append_range(args);
    return dealias(substitute(^^make_func_meta,
        template_args | std::views::transform([](auto arg) {
            return reflect_constant(arg);
        })
    ));
}

// Creates a function from a range, where the first element is the return value
// and the rest are arguments.
template <std::meta::reflection_range R = std::initializer_list<std::meta::info>>
consteval std::meta::info make_func(R&& ret_and_args) {
    return dealias(substitute(^^make_func_meta,
        std::forward<R>(ret_and_args) | std::views::transform([](auto arg) {
            return reflect_constant(arg);
        })
    ));
}

// Creates a function type with the given argument as the first.
consteval std::meta::info prepend_arg(std::meta::info to_prepend, std::meta::info func) {
    auto params = parameters_of(func);
    auto args = std::views::concat(
        std::views::single(return_type_of(func)),
        std::views::single(to_prepend),
        params
    );

    return make_func(args);
}

// Creates a function type with the given argument as the final parameter.
consteval std::meta::info append_arg(std::meta::info to_append, std::meta::info func) {
    std::vector args{return_type_of(func)};
    args.append_range(parameters_of(func));
    args.push_back(to_append);

    return make_func(args);
}

// Removes an an argument type from a function's parameter list.
consteval std::meta::info remove_arg(std::meta::info func,
                                     std::meta::info to_remove) {
    auto params = parameters_of(func);
    return make_func(return_type_of(func), params
        | std::views::filter([to_remove](auto param) {
        return decay(param) != to_remove;
    }));
}
}

#endif
// clang-format off

#ifndef RJK_REMOVE_FN_QUALIFIERS_HPP
#define RJK_REMOVE_FN_QUALIFIERS_HPP

// clang-format off

#ifndef RJK_FLAG_ENUM_HPP
#define RJK_FLAG_ENUM_HPP

#include <utility>

namespace rjk::detail {

// Use in an attribute like [[=detail::flag_enum]] to mark that an enumeration
// type consists only of flags.
constexpr inline struct{} flag_enum{};

consteval bool has_annotation(std::meta::info obj, std::meta::info annotation) {
    return std::ranges::any_of(annotations_of(obj),
        [annotation](auto a) { return type_of(a) == type_of(annotation); });
}

template <typename T>
concept is_flag_enum = std::is_enum_v<T> && requires { T::none == static_cast<T>(0); }
    && has_annotation(^^T, ^^flag_enum);

// Now every type with the flag_enum attribute gets the following operators for free.

template <is_flag_enum EnumType>
constexpr EnumType operator|(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) | std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator|=(EnumType& lhs, EnumType rhs) {
    lhs = lhs | rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator&(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) & std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator&=(EnumType& lhs, EnumType rhs) {
    lhs = lhs & rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator~(EnumType operand) {
    return static_cast<EnumType>(~std::to_underlying(operand));
}
}

#endif

#include <meta>

namespace rjk {
template <typename T>
struct remove_fn_qualifiers_trait {
    using type = T;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) &> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const &> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) &&> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const &&> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) & noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const & noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) && noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const && noexcept> {
    using type = Ret(Args...);
};

template <typename T>
using remove_fn_qualifiers_t = remove_fn_qualifiers_trait<T>::type;

// TODO: remove once GCC fixes reference return type bug
template <std::meta::info T>
using remove_fn_qualifiers_meta = remove_fn_qualifiers_t<typename [:T:]>;

// Removes const, reference qualifiers, and noexcept.
consteval std::meta::info remove_fn_qualifiers(std::meta::info type) {
    return dealias(substitute(^^remove_fn_qualifiers_meta, {reflect_constant(type)}));
}

namespace detail {

enum struct [[=flag_enum]] fn_qualifiers {
    none = 0,
    is_const = 1,
    lvalue_ref = 1 << 1,
    rvalue_ref = 1 << 2
};

// Checks the qualifiers of a type.
consteval fn_qualifiers qualifiers_of_type(std::meta::info type) {
    auto qualifiers = fn_qualifiers::none;
    if (is_const(remove_reference(type))) {
        qualifiers |= fn_qualifiers::is_const;
    }
    if (is_lvalue_reference_type(type) &&
        !static_cast<bool>(qualifiers & fn_qualifiers::is_const)) {
        qualifiers |= fn_qualifiers::lvalue_ref;
    }
    if (is_rvalue_reference_type(type)) {
        qualifiers |= fn_qualifiers::rvalue_ref;
    }
    return qualifiers;
}

// Checks the qualifiers of a function.
consteval fn_qualifiers qualifiers_of(std::meta::info function) {
    auto qualifiers = fn_qualifiers::none;
    if (is_const(function)) {
        qualifiers |= fn_qualifiers::is_const;
    }
    if (is_lvalue_reference_qualified(function)) {
        qualifiers |= fn_qualifiers::lvalue_ref;
    }
    if (is_rvalue_reference_qualified(function)) {
        qualifiers |= fn_qualifiers::rvalue_ref;
    }
    return qualifiers;
}

// Searches the parameter list for a parameter with the type of target, then
// returns the qualifiers of that type.
consteval fn_qualifiers qualifiers_of_target(std::meta::info functionType,
                                             std::meta::info target) {
    const auto params = parameters_of(functionType);
    const auto itr = std::ranges::find_if(params,
        [target](auto param) { return decay(param) == target; }
    );
    return qualifiers_of_type(*itr);
}

}
}

#endif
// clang-format off

#ifndef RJK_REMOVE_NOEXCEPT_HPP
#define RJK_REMOVE_NOEXCEPT_HPP

namespace rjk {
template <typename Func>
struct remove_noexcept_trait {
    using type = Func;
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) noexcept> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) const noexcept> {
    using type = Ret(Args...) const;
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) & noexcept> {
    using type = Ret(Args...) &;
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) const & noexcept> {
    using type = Ret(Args...) const &;
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) && noexcept> {
    using type = Ret(Args...) &&;
};

template <typename Ret, typename... Args>
struct remove_noexcept_trait<Ret(Args...) const && noexcept> {
    using type = Ret(Args...) const &&;
};

template <typename T>
using remove_noexcept_t = remove_noexcept_trait<T>::type;

// TODO: remove once GCC fixes reference return type bug
template <std::meta::info T>
using remove_noexcept_meta = remove_noexcept_t<typename [:T:]>;

consteval std::meta::info remove_noexcept(std::meta::info type) {
    return dealias(substitute(^^remove_noexcept_meta, {reflect_constant(type)}));
}
}

#endif
// clang-format off

#ifndef RJK_DISPLAY_ERROR_HPP
#define RJK_DISPLAY_ERROR_HPP

