// clang-format off

#ifndef RJK_DUCK_VIEW_HPP
#define RJK_DUCK_VIEW_HPP

#include "ducwk.hpp"

/*** Start of inlined file: subsumption_utils.hpp ***/
// clang-format off

#ifndef RJK_SUBSUMPTION_UTILS_HPP
#define RJK_SUBSUMPTION_UTILS_HPP

#include <meta>


/*** Start of inlined file: vtable_generator.hpp ***/
// clang-format off

#ifndef RJK_VTABLE_GENERATOR_HPP
#define RJK_VTABLE_GENERATOR_HPP


/*** Start of inlined file: vtable_fn_maker.hpp ***/
// clang-format off

#ifndef RJK_VTABLE_FN_MAKER_HPP
#define RJK_VTABLE_FN_MAKER_HPP


/*** Start of inlined file: do_binary_op.hpp ***/
// This file was automatically generated by generate_operators.py.

#ifndef RJK_DO_BINARY_OP_HPP
#define RJK_DO_BINARY_OP_HPP

#include <meta>

/*** Start of inlined file: fn_traits.hpp ***/
// clang-format off

#ifndef RJK_FN_TRAITS_HPP
#define RJK_FN_TRAITS_HPP

#include <type_traits>
#include <meta>
#include <ranges>

namespace rjk::detail {

// Allows easy translation between concepts and meta-functions.
template <typename T, auto Func>
concept evaluate = Func(^^T);

template <typename Ret, typename... Args>
using make_func_t = Ret(Args...);

template <std::meta::info Ret, std::meta::info... Args>
using make_func_meta = make_func_t<typename [:Ret:], typename [:Args:]...>;

// Creates a function type with the provided return type and arguments.
template <std::meta::reflection_range R = std::initializer_list<std::meta::info>>
consteval std::meta::info make_func(std::meta::info ret, R&& args) {
    std::vector template_args{ret};
    template_args.append_range(args);
    return dealias(substitute(^^make_func_meta,
        template_args | std::views::transform([](auto arg) {
            return reflect_constant(arg);
        })
    ));
}

// Creates a function from a range, where the first element is the return value
// and the rest are arguments.
template <std::meta::reflection_range R = std::initializer_list<std::meta::info>>
consteval std::meta::info make_func(R&& ret_and_args) {
    return dealias(substitute(^^make_func_meta,
        std::forward<R>(ret_and_args) | std::views::transform([](auto arg) {
            return reflect_constant(arg);
        })
    ));
}

// Creates a function type with the given argument as the first.
consteval std::meta::info prepend_arg(std::meta::info to_prepend, std::meta::info func) {
    auto params = parameters_of(func);
    auto args = std::views::concat(
        std::views::single(return_type_of(func)),
        std::views::single(to_prepend),
        params
    );

    return make_func(args);
}

// Creates a function type with the given argument as the final parameter.
consteval std::meta::info append_arg(std::meta::info to_append, std::meta::info func) {
    std::vector args{return_type_of(func)};
    args.append_range(parameters_of(func));
    args.push_back(to_append);

    return make_func(args);
}

// Removes an an argument type from a function's parameter list.
consteval std::meta::info remove_arg(std::meta::info func,
                                     std::meta::info to_remove) {
    auto params = parameters_of(func);
    return make_func(return_type_of(func), params
        | std::views::filter([to_remove](auto param) {
        return decay(param) != to_remove;
    }));
}
}

#endif
/*** End of inlined file: fn_traits.hpp ***/


namespace rjk::detail {

template <std::meta::operators Op, bool Noexcept, typename Lhs, typename Rhs>
constexpr decltype(auto) do_binary_op(Lhs&& lhs, Rhs&& rhs) noexcept(Noexcept) {
    using enum std::meta::operators;
    if constexpr (Op == op_plus) return std::forward<Lhs>(lhs) + std::forward<Rhs>(rhs);
    if constexpr (Op == op_minus) return std::forward<Lhs>(lhs) - std::forward<Rhs>(rhs);
    if constexpr (Op == op_star) return std::forward<Lhs>(lhs) * std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand) return std::forward<Lhs>(lhs) & std::forward<Rhs>(rhs);
    if constexpr (Op == op_slash) return std::forward<Lhs>(lhs) / std::forward<Rhs>(rhs);
    if constexpr (Op == op_percent) return std::forward<Lhs>(lhs) % std::forward<Rhs>(rhs);
    if constexpr (Op == op_caret) return std::forward<Lhs>(lhs) ^ std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe) return std::forward<Lhs>(lhs) | std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_less) return std::forward<Lhs>(lhs) << std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_greater) return std::forward<Lhs>(lhs) >> std::forward<Rhs>(rhs);
    if constexpr (Op == op_comma) return std::forward<Lhs>(lhs) , std::forward<Rhs>(rhs);
    if constexpr (Op == op_arrow_star) return std::forward<Lhs>(lhs) ->* std::forward<Rhs>(rhs);
    if constexpr (Op == op_plus_equals) return std::forward<Lhs>(lhs) += std::forward<Rhs>(rhs);
    if constexpr (Op == op_minus_equals) return std::forward<Lhs>(lhs) -= std::forward<Rhs>(rhs);
    if constexpr (Op == op_star_equals) return std::forward<Lhs>(lhs) *= std::forward<Rhs>(rhs);
    if constexpr (Op == op_slash_equals) return std::forward<Lhs>(lhs) /= std::forward<Rhs>(rhs);
    if constexpr (Op == op_percent_equals) return std::forward<Lhs>(lhs) %= std::forward<Rhs>(rhs);
    if constexpr (Op == op_caret_equals) return std::forward<Lhs>(lhs) ^= std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand_equals) return std::forward<Lhs>(lhs) &= std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe_equals) return std::forward<Lhs>(lhs) |= std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_less_equals) return std::forward<Lhs>(lhs) <<= std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_greater_equals) return std::forward<Lhs>(lhs) >>= std::forward<Rhs>(rhs);
    if constexpr (Op == op_equals_equals) return std::forward<Lhs>(lhs) == std::forward<Rhs>(rhs);
    if constexpr (Op == op_exclamation_equals) return std::forward<Lhs>(lhs) != std::forward<Rhs>(rhs);
    if constexpr (Op == op_less) return std::forward<Lhs>(lhs) < std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater) return std::forward<Lhs>(lhs) > std::forward<Rhs>(rhs);
    if constexpr (Op == op_less_equals) return std::forward<Lhs>(lhs) <= std::forward<Rhs>(rhs);
    if constexpr (Op == op_greater_equals) return std::forward<Lhs>(lhs) >= std::forward<Rhs>(rhs);
    if constexpr (Op == op_spaceship) return std::forward<Lhs>(lhs) <=> std::forward<Rhs>(rhs);
    if constexpr (Op == op_ampersand_ampersand) return std::forward<Lhs>(lhs) && std::forward<Rhs>(rhs);
    if constexpr (Op == op_pipe_pipe) return std::forward<Lhs>(lhs) || std::forward<Rhs>(rhs);
    if constexpr (Op == op_plus_plus) return std::forward<Lhs>(lhs)++;
    if constexpr (Op == op_minus_minus) return std::forward<Lhs>(lhs)--;
}

template <std::meta::operators Op, bool Noexcept, typename Lhs, typename LhsRef, typename Rhs, typename RhsRef, auto CheckRet>
consteval bool check_binary_op() {
    using enum std::meta::operators;
    if constexpr (Op == op_plus)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) + static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() + std::declval<RhsRef>());
    if constexpr (Op == op_minus)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) - static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() - std::declval<RhsRef>());
    if constexpr (Op == op_star)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) * static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() * std::declval<RhsRef>());
    if constexpr (Op == op_ampersand)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) & static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() & std::declval<RhsRef>());
    if constexpr (Op == op_slash)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) / static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() / std::declval<RhsRef>());
    if constexpr (Op == op_percent)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) % static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() % std::declval<RhsRef>());
    if constexpr (Op == op_caret)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) ^ static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() ^ std::declval<RhsRef>());
    if constexpr (Op == op_pipe)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) | static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() | std::declval<RhsRef>());
    if constexpr (Op == op_less_less)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) << static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() << std::declval<RhsRef>());
    if constexpr (Op == op_greater_greater)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) >> static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() >> std::declval<RhsRef>());
    if constexpr (Op == op_comma)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) , static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() , std::declval<RhsRef>());
    if constexpr (Op == op_arrow_star)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) ->* static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() ->* std::declval<RhsRef>());
    if constexpr (Op == op_plus_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) += static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() += std::declval<RhsRef>());
    if constexpr (Op == op_minus_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) -= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() -= std::declval<RhsRef>());
    if constexpr (Op == op_star_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) *= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() *= std::declval<RhsRef>());
    if constexpr (Op == op_slash_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) /= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() /= std::declval<RhsRef>());
    if constexpr (Op == op_percent_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) %= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() %= std::declval<RhsRef>());
    if constexpr (Op == op_caret_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) ^= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() ^= std::declval<RhsRef>());
    if constexpr (Op == op_ampersand_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) &= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() &= std::declval<RhsRef>());
    if constexpr (Op == op_pipe_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) |= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() |= std::declval<RhsRef>());
    if constexpr (Op == op_less_less_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) <<= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() <<= std::declval<RhsRef>());
    if constexpr (Op == op_greater_greater_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) >>= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() >>= std::declval<RhsRef>());
    if constexpr (Op == op_equals_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) == static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() == std::declval<RhsRef>());
    if constexpr (Op == op_exclamation_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) != static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() != std::declval<RhsRef>());
    if constexpr (Op == op_less)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) < static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() < std::declval<RhsRef>());
    if constexpr (Op == op_greater)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) > static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() > std::declval<RhsRef>());
    if constexpr (Op == op_less_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) <= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() <= std::declval<RhsRef>());
    if constexpr (Op == op_greater_equals)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) >= static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() >= std::declval<RhsRef>());
    if constexpr (Op == op_spaceship)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) <=> static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() <=> std::declval<RhsRef>());
    if constexpr (Op == op_ampersand_ampersand)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) && static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() && std::declval<RhsRef>());
    if constexpr (Op == op_pipe_pipe)
        if constexpr (requires(Lhs lhs, Rhs rhs) { { static_cast<LhsRef>(lhs) || static_cast<RhsRef>(rhs) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>() || std::declval<RhsRef>());
    if constexpr (Op == op_plus_plus)
        if constexpr (requires(Lhs lhs) { { static_cast<LhsRef>(lhs)++ } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>()++);
    if constexpr (Op == op_minus_minus)
        if constexpr (requires(Lhs lhs) { { static_cast<LhsRef>(lhs)-- } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<LhsRef>()--);
    return false;
}

}

#endif
/*** End of inlined file: do_binary_op.hpp ***/


/*** Start of inlined file: do_unary_op.hpp ***/
// This file was automatically generated by generate_operators.py.

#ifndef RJK_DO_UNARY_OP_HPP
#define RJK_DO_UNARY_OP_HPP

#include <meta>

namespace rjk::detail {

template <std::meta::operators Op, bool Noexcept, typename Operand>
constexpr decltype(auto) do_unary_op(Operand&& operand) noexcept(Noexcept) {
    using enum std::meta::operators;
    if constexpr (Op == op_tilde) return ~std::forward<Operand>(operand);
    if constexpr (Op == op_exclamation) return !std::forward<Operand>(operand);
    if constexpr (Op == op_plus_plus) return ++std::forward<Operand>(operand);
    if constexpr (Op == op_minus_minus) return --std::forward<Operand>(operand);
    if constexpr (Op == op_plus) return +std::forward<Operand>(operand);
    if constexpr (Op == op_minus) return -std::forward<Operand>(operand);
    if constexpr (Op == op_star) return *std::forward<Operand>(operand);
    if constexpr (Op == op_ampersand) return &std::forward<Operand>(operand);
    if constexpr (Op == op_arrow) return std::forward<Operand>(operand).operator->();
}

template <std::meta::operators Op, bool Noexcept, typename ObjType, typename RefType, auto CheckRet>
consteval bool check_unary_op() {
    using enum std::meta::operators;
    if constexpr (Op == op_tilde)
        if constexpr (requires(ObjType operand) { { ~static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(~std::declval<RefType>());
    if constexpr (Op == op_exclamation)
        if constexpr (requires(ObjType operand) { { !static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(!std::declval<RefType>());
    if constexpr (Op == op_plus_plus)
        if constexpr (requires(ObjType operand) { { ++static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(++std::declval<RefType>());
    if constexpr (Op == op_minus_minus)
        if constexpr (requires(ObjType operand) { { --static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(--std::declval<RefType>());
    if constexpr (Op == op_plus)
        if constexpr (requires(ObjType operand) { { +static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(+std::declval<RefType>());
    if constexpr (Op == op_minus)
        if constexpr (requires(ObjType operand) { { -static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(-std::declval<RefType>());
    if constexpr (Op == op_star)
        if constexpr (requires(ObjType operand) { { *static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(*std::declval<RefType>());
    if constexpr (Op == op_ampersand)
        if constexpr (requires(ObjType operand) { { &static_cast<RefType>(operand) } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(&std::declval<RefType>());
    if constexpr (Op == op_arrow)
        if constexpr (requires(ObjType operand) { { static_cast<RefType>(operand).operator->() } -> evaluate<CheckRet>; })
            return !Noexcept || noexcept(std::declval<RefType>().operator->());
    return false;
}

}

#endif
/*** End of inlined file: do_unary_op.hpp ***/


/*** Start of inlined file: remove_fn_qualifiers.hpp ***/
// clang-format off

#ifndef RJK_REMOVE_FN_QUALIFIERS_HPP
#define RJK_REMOVE_FN_QUALIFIERS_HPP


/*** Start of inlined file: flag_enum.hpp ***/
// clang-format off

#ifndef RJK_FLAG_ENUM_HPP
#define RJK_FLAG_ENUM_HPP

#include <utility>

namespace rjk::detail {

// Use in an attribute like [[=detail::flag_enum]] to mark that an enumeration
// type consists only of flags.
constexpr inline struct{} flag_enum{};

consteval bool has_annotation(std::meta::info obj, std::meta::info annotation) {
    return std::ranges::any_of(annotations_of(obj),
        [annotation](auto a) { return type_of(a) == type_of(annotation); });
}

template <typename T>
concept is_flag_enum = std::is_enum_v<T> && requires { T::none == static_cast<T>(0); }
    && has_annotation(^^T, ^^flag_enum);

// Now every type with the flag_enum attribute gets the following operators for free.

template <is_flag_enum EnumType>
constexpr EnumType operator|(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) | std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator|=(EnumType& lhs, EnumType rhs) {
    lhs = lhs | rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator&(EnumType lhs, EnumType rhs) {
    return static_cast<EnumType>(std::to_underlying(lhs) & std::to_underlying(rhs));
}

template <is_flag_enum EnumType>
constexpr EnumType& operator&=(EnumType& lhs, EnumType rhs) {
    lhs = lhs & rhs;
    return lhs;
}

template <is_flag_enum EnumType>
constexpr EnumType operator~(EnumType operand) {
    return static_cast<EnumType>(~std::to_underlying(operand));
}
}

#endif
/*** End of inlined file: flag_enum.hpp ***/

#include <meta>

namespace rjk {
template <typename T>
struct remove_fn_qualifiers_trait {
    using type = T;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) &> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const &> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) &&> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const &&> {
    using type = Ret(Args...);
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) & noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const & noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) && noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename Ret, typename... Args>
struct remove_fn_qualifiers_trait<Ret(Args...) const && noexcept> {
    using type = Ret(Args...) noexcept;
};

template <typename T>
using remove_fn_qualifiers_t = remove_fn_qualifiers_trait<T>::type;

// TODO: remove once GCC fixes reference return type bug
template <std::meta::info T>
using remove_fn_qualifiers_meta = remove_fn_qualifiers_t<typename [:T:]>;

// Removes const, reference qualifiers, and noexcept.
consteval std::meta::info remove_fn_qualifiers(std::meta::info type) {
    return dealias(substitute(^^remove_fn_qualifiers_meta, {reflect_constant(type)}));
}

namespace detail {

enum struct [[=flag_enum]] fn_qualifiers {
    none = 0,
    is_const = 1,
    lvalue_ref = 1 << 1,
    rvalue_ref = 1 << 2
};

// Checks the qualifiers of a type.
consteval fn_qualifiers qualifiers_of_type(std::meta::info type) {
    auto qualifiers = fn_qualifiers::none;
    if (is_const(remove_reference(type))) {
        qualifiers |= fn_qualifiers::is_const;
    }
    if (is_lvalue_reference_type(type) &&
        !static_cast<bool>(qualifiers & fn_qualifiers::is_const)) {
        qualifiers |= fn_qualifiers::lvalue_ref;
    }
    if (is_rvalue_reference_type(type)) {
        qualifiers |= fn_qualifiers::rvalue_ref;
    }
    return qualifiers;
}

// Checks the qualifiers of a function.
consteval fn_qualifiers qualifiers_of(std::meta::info function) {
    auto qualifiers = fn_qualifiers::none;
    if (is_const(function)) {
        qualifiers |= fn_qualifiers::is_const;
    }
    if (is_lvalue_reference_qualified(function)) {
        qualifiers |= fn_qualifiers::lvalue_ref;
    }
    if (is_rvalue_reference_qualified(function)) {
        qualifiers |= fn_qualifiers::rvalue_ref;
    }
    return qualifiers;
}

// Searches the parameter list for a parameter with the type of target, then
// returns the qualifiers of that type.
consteval fn_qualifiers qualifiers_of_target(std::meta::info functionType,
                                             std::meta::info target) {
    const auto params = parameters_of(functionType);
    const auto itr = std::ranges::find_if(params,
        [target](auto param) { return decay(param) == target; }
    );
    return qualifiers_of_type(*itr);
}

}
}

#endif
/*** End of inlined file: remove_fn_qualifiers.hpp ***/


/*** Start of inlined file: duck_tags.hpp ***/
// clang-format off

#ifndef RJK_DUCK_TAGS_HPP
#define RJK_DUCK_TAGS_HPP


/*** Start of inlined file: fixed_string.hpp ***/
// clang-format off

#ifndef RJK_FIXED_STRING_HPP
#define RJK_FIXED_STRING_HPP

#include <meta>

namespace rjk {

// Compile-time string primitive. We need this to be able to pass
// strings as template arguments.
struct fixed_string {
    consteval fixed_string() = default;

    template <std::size_t N>
    consteval fixed_string(const char (&str)[N]) {
        m_data = std::define_static_string(str);
        m_length = N - 1;
    }

    consteval explicit fixed_string(std::string_view str) {
        m_data = std::define_static_string(str);
        m_length = str.size();
    }

    consteval bool operator==(const fixed_string&) const = default;

    consteval auto operator+(const fixed_string& other) const {
        std::string result_str{m_data};
        result_str += other.m_data;

        return fixed_string{std::string_view{result_str}};
    }

    consteval const char* data() const { return m_data; }
    consteval std::size_t size() const { return m_length; }

    consteval explicit operator std::string_view() const {
        return {m_data, m_length};
    }

    const char* m_data{};
    std::size_t m_length{};
};
}

#endif
/*** End of inlined file: fixed_string.hpp ***/


/*** Start of inlined file: display_error.hpp ***/
// clang-format off

#ifndef RJK_DISPLAY_ERROR_HPP
#define RJK_DISPLAY_ERROR_HPP

namespace rjk::detail {
template <fixed_string Error>
consteval void display_error_impl() {
    static_assert(false, Error);
}

// Displays a static assertion based on non-constant branching. In general,
// we prefer this to compile-time exceptions for the slightly more readable
// error messages and the compatability with -fno-exceptions.
consteval void display_error(std::string_view message) {
    const auto message_refl = std::meta::reflect_constant(fixed_string{message});
    const auto error_func = substitute(^^display_error_impl, {message_refl});
    extract<void (*)()>(error_func);
}
}

#endif

/*** End of inlined file: display_error.hpp ***/


/*** Start of inlined file: meta_util.hpp ***/
// clang-format off

#ifndef RJK_META_UTIL_HPP
#define RJK_META_UTIL_HPP

#include <functional>
#include <meta>
#include <ranges>

namespace rjk::detail {

// Searches the given type using search_func, and also all of the bases of that
// type.
consteval std::vector<std::meta::info> recursive_search(std::meta::info type, auto search_func,
    std::meta::access_context ctx, auto... search_args) {
    auto result = search_func(type, search_args...);
    auto bases = bases_of(type, ctx);
    auto base_results = bases
        | std::views::transform(std::meta::type_of)
        | std::views::transform([=](std::meta::info type) {
            return recursive_search(type, search_func, ctx, search_args...);
        })
        | std::views::join;
    result.append_range(base_results);

    return result;
}

// goes through all members of a class, including its base classes' members.
consteval std::vector<std::meta::info> all_members_of(std::meta::info class_type) {
    const auto ctx = std::meta::access_context::unprivileged();

    return recursive_search(class_type, std::meta::members_of, ctx, ctx);
}

// returns a vector of the provided type and all of its bases, all the way up
// the inheritance chain.
consteval std::vector<std::meta::info> family_tree_for(std::meta::info class_type) {
    const auto ctx = std::meta::access_context::unprivileged();

    return recursive_search(class_type, [](auto base) { return std::vector{base}; }, ctx);
}
}

#endif

/*** End of inlined file: meta_util.hpp ***/

#include <functional>
#include <ranges>

namespace rjk {

template <typename Type, typename RelevantTrait, bool PrettyError, typename... Tags>
consteval bool satisfies_tags();

template <typename T>
concept function_signature = std::is_function_v<T>;

using enum std::meta::operators;

template <typename E, bool Enumerable = std::meta::is_enumerable_type(^^E)>
    requires std::is_enum_v<E>
constexpr std::string_view enum_to_string(E value) {
    if constexpr (Enumerable) {
        template for (constexpr auto e : std::define_static_array(std::meta::enumerators_of(^^E))) {
            if (value == [:e:]) {
                return std::meta::identifier_of(e);
            }
        }
    } else {
        return "<unnamed>";
    }
}

template <fixed_string Identifier, function_signature Func>
struct has_fn {};

template <std::meta::operators Operator, function_signature Func>
struct has_op {};

struct copy_tag{};

// TODO: Remove when GCC fixes bug
template <fixed_string Identifier, std::meta::info Func>
using has_fn_meta = has_fn<Identifier, typename [:Func:]>;

// TODO: Remove when GCC fixes bug
template <std::meta::operators Operator, std::meta::info Func>
using has_op_meta = has_op<Operator, typename [:Func:]>;

// Used for denoting the relative location of two ducks in a has_op signature.
struct self{};

// Can be plugged into rjk::policy.
template <typename T>
concept duck_tag = std::meta::has_template_arguments(^^T) && (
    template_of(^^T) == ^^has_fn ||
    template_of(^^T) == ^^has_op);

// Plugged into rjk::duck.
template <duck_tag... Tags>
struct policy{};

template <typename Func>
concept is_meta_predicate = std::invocable<Func, std::meta::info> &&
    std::same_as<std::invoke_result_t<Func, std::meta::info>, bool>;

// Models a trait based on the type's public interface and the provided predicate.
template <typename T, is_meta_predicate auto Predicate =
    [] (std::meta::info) consteval { return true; }>
struct like {};

template <is_meta_predicate auto... Predicates>
constexpr inline auto all_of = [](std::meta::info member) {
    return (std::invoke(Predicates, member) && ...);
};

template <is_meta_predicate auto... Predicates>
constexpr inline auto any_of = [](std::meta::info member) {
    return (std::invoke(Predicates, member) || ...);
};

template <is_meta_predicate auto... Predicates>
constexpr inline auto none_of = [](std::meta::info member) {
    return !(std::invoke(Predicates, member) || ...);
};

template <fixed_string... Whitelist>
constexpr inline auto include = [](std::meta::info member) {
    if (!has_identifier(member)) {
        return false;
    }
    const auto whitelist = std::array<fixed_string, sizeof...(Whitelist)>{Whitelist...}
        | std::views::transform([](auto str) {
            return std::string_view{str};
        });
    return std::ranges::contains(whitelist, identifier_of(member));
};

template <fixed_string... Blacklist>
constexpr inline auto exclude = [](std::meta::info member) {
    if (!has_identifier(member)) {
        return true;
    }

    const auto blacklist = std::array<fixed_string, sizeof...(Blacklist)>{Blacklist...}
        | std::views::transform([](auto str) {
            return std::string_view{str};
        });
    return !std::ranges::contains(blacklist, identifier_of(member));
};

// Passed as a policy to rjk::duck to allow copying.
using copyable = policy<copy_tag>;

// The following are meant to be used as attributes.

// [[=rjk::trait]] specifies that a struct will be used as a trait.
constexpr inline struct{} trait{};

// [[=rjk::right_side]] specifies that an operator function is being defined with self as the last argument.
constexpr inline struct{} right_side{};

// [[=rjk::both_sides]] specifies that an operator function needs both self + T and T + self.
constexpr inline struct{} both_sides{};

// [[=rjk::perf_options]] specifies a trait that changes the default performance options for
// rjk::duck. Currently, these means customizing sbo_size and sbo_alignment.
constexpr inline struct{} perf_options{};

template <typename T>
concept is_policy = (has_template_arguments(^^T) && template_of(^^T) == ^^policy);

template <typename T>
concept is_like = (has_template_arguments(^^T) && template_of(^^T) == ^^like);

template <typename T>
concept is_perf_option = detail::has_annotation(^^T, ^^perf_options);

template <typename T>
concept is_trait = (
    is_policy<T> || is_like<T> || is_perf_option<T> ||
    detail::has_annotation(^^T, ^^trait));

template <is_trait... Traits>
class duck;

template <is_trait... Traits>
class duck_view;

template <is_trait... Traits>
class duck_ptr;

// Allows users to add an additional
template <typename T, is_trait Trait>
struct impl {};

namespace detail {
consteval std::string format_func_name(auto name, std::meta::info signature) {
    const auto disp_str = display_string_of(signature);
    return std::string{disp_str.substr(0, disp_str.find('('))}
        + " " + name + disp_str.substr(disp_str.find('('));
}

consteval std::vector<std::meta::info> members_to_tags(std::meta::info trait);

// NOTE: duck_ptr is not a duck type, it's just a wrapper around duck_view.
consteval static bool is_duck_type(std::meta::info type) {
    type = dealias(decay(type));

    if (!has_template_arguments(type)) {
        return false;
    }
    if (template_of(type) != ^^duck && template_of(type) != ^^duck_view) {
        return false;
    }
    return true;
}

consteval static bool is_duck_container(std::meta::info type) {
    return has_template_arguments(type)
        && is_type(type)
        && template_of(type) == ^^duck;
}

template <typename TraitRet, typename ActualRet>
consteval bool is_conversion_noexcept_impl() {
    if constexpr (is_duck_container(^^TraitRet)) {
        return TraitRet::template nothrow_constructor<std::decay_t<ActualRet>, ActualRet>;
    } else {
        return true;
    }
};

consteval bool is_conversion_noexcept(std::meta::info trait_ret, std::meta::info actual_ret) {
    return std::invoke(extract<bool(*)()>(substitute(^^is_conversion_noexcept_impl, {trait_ret, actual_ret})));
}

consteval bool is_return_compatible(std::meta::info ret,
    std::meta::info tested_type,
    std::meta::info trait_ret,
    bool pretty_error) {

    if (ret == trait_ret) {
        return true;
    }
    if (!has_template_arguments(trait_ret)) {
        return false;
    }
    if (!detail::is_duck_type(trait_ret) && template_of(trait_ret) != ^^duck_ptr) {
        return false;
    }

    const auto args = template_arguments_of(trait_ret)
        | std::views::transform(members_to_tags)
        | std::views::join
        | std::ranges::to<std::vector>();
    const auto decayed_ret = decay(remove_pointer(decay(ret)));

    const auto meets_tags = [&] {
        return std::ranges::all_of(template_arguments_of(trait_ret), [&](auto trait) {
            const auto sub_args = std::views::concat(
                std::array{decayed_ret, trait, std::meta::reflect_constant(pretty_error)},
                members_to_tags(trait)
            );
            const auto meets_trait = std::invoke(
                extract<bool(*)()>(substitute(^^satisfies_tags, sub_args)));
            return meets_trait;
        });
    };

    if (template_of(trait_ret) == ^^duck_view) {
        if (!is_lvalue_reference_type(ret)) {
            return false;
        }

        const bool all_const = std::ranges::all_of(
            template_arguments_of(trait_ret), std::meta::is_const);

        if (!all_const && is_const(remove_reference(ret))) {
            return false;
        }

        if (decay(tested_type) != decayed_ret) {
            return meets_tags();
        }
        return true;
    }
    if (template_of(trait_ret) == ^^duck_ptr) {
        if (!is_pointer_type(ret)) {
            return false;
        }

        const bool all_const = std::ranges::all_of(
            template_arguments_of(trait_ret), std::meta::is_const);

        if (!all_const && is_const(remove_reference(ret))) {
            return false;
        }

        if (decay(tested_type) != decayed_ret) {
            return meets_tags();
        }
        return true;
    }
    if (template_of(trait_ret) == ^^duck) {
        if (is_lvalue_reference_type(ret)) {
            return false;
        }
        if (is_rvalue_reference_type(ret) && is_const(remove_reference(ret))) {
            return false;
        }

        if (decay(tested_type) != decayed_ret) {
            return meets_tags();
        }
        return true;
    }
    return false;
}

consteval bool is_compatible_sig_in_impl(std::meta::info member, std::meta::info sig,
    std::meta::info test_type, bool pretty_error) {
    const auto same_params = std::ranges::equal(
        parameters_of(member) | std::views::drop(1)
        | std::views::transform(std::meta::type_of)
        | std::views::transform(std::meta::dealias),
        parameters_of(sig)
    );

    auto func_qualifiers = detail::qualifiers_of(sig);
    if (func_qualifiers == detail::fn_qualifiers::none) {
        // If there are no qualifiers at all, the function is valid for both
        // non-const lvalue and rvalues. When matching against the function
        // signature in rjk::impl, we want to look for the forwarding reference.
        func_qualifiers |= detail::fn_qualifiers::rvalue_ref;
    }

    const auto same_qualifiers = detail::qualifiers_of_target(type_of(member), test_type) == func_qualifiers;

    const auto same_returns = detail::is_return_compatible(
        dealias(return_type_of(member)), test_type,
        dealias(return_type_of(sig)), pretty_error);

    const auto same_noexcept = !is_noexcept(sig) || is_noexcept(member);

    return same_params && same_qualifiers && same_returns && same_noexcept;
}

consteval bool is_compatible_sig(std::meta::info member, std::meta::info sig,
    std::meta::info test_type, bool pretty_error) {

    const auto same_params =std::ranges::equal(
        parameters_of(member)
        | std::views::transform(std::meta::type_of)
        | std::views::transform(std::meta::dealias),
        parameters_of(sig)
    );

    const auto same_qualifiers = detail::qualifiers_of(member) == detail::qualifiers_of(sig);

    const auto ret = dealias(return_type_of(member));
    const auto trait_ret = dealias(return_type_of(sig));
    const auto same_returns = detail::is_return_compatible(
        ret, test_type, trait_ret, pretty_error);
    if (same_returns && is_noexcept(sig) &&
        !is_conversion_noexcept(trait_ret, ret)) {
        return false;
    }

    const auto same_noexcept = !is_noexcept(sig) || is_noexcept(member);

    return same_params && same_qualifiers && same_returns && same_noexcept;
}

consteval std::optional<std::meta::info> find_impl_specialization(
    std::meta::info type, std::meta::info trait, std::string_view member_name,
    std::meta::info full_sig, bool pretty_error) {
    const auto bases = family_tree_for(trait);
    for (const auto base : bases) {
        const auto impl_struct = substitute(^^impl, {type, remove_const(base)});
        const auto members = members_of(impl_struct, std::meta::access_context::unprivileged());
        const auto member = std::ranges::find_if(members, [=](auto m) {
            if (!has_identifier(m)) {
                return false;
            }
            if (identifier_of(m) != member_name) {
                return false;
            }
            if (is_function(m)) {
                return is_compatible_sig_in_impl(
                    m, full_sig, type, pretty_error);
            }
            if (is_function_template(m)) {
                if (!can_substitute(m, {type})) {
                    return false;
                }
                const auto func = substitute(m, {type});
                if (!is_function(func)) {
                    return false;
                }
                return is_compatible_sig_in_impl(func,
                    full_sig, type, pretty_error);
            }
            return false;
        });

        if (member != members.end()) {
            return *member;
        }
    }
    return std::nullopt;
}
}

template <typename Type, typename RelevantTrait, std::meta::info Tag, bool PrettyErrors>
consteval bool satisfies_fn_tag() {
    static_assert(is_class_type(^^Type));

    constexpr static auto type_members = define_static_array(detail::all_members_of(^^Type));
    constexpr static auto name = std::string_view{[:template_arguments_of(Tag)[0]:]};
    constexpr static auto sig = template_arguments_of(Tag)[1];

    constexpr static bool meets_tag = std::ranges::any_of(type_members, [](auto member) {
        return has_identifier(member) &&
            identifier_of(member) == name &&
            is_function(member) && detail::is_compatible_sig(member, sig, ^^Type, PrettyErrors);
    });

    if constexpr (meets_tag) {
        return true;
    } else {
        const auto specialization = detail::find_impl_specialization(
            ^^Type, ^^RelevantTrait, name, sig, PrettyErrors);
        if (specialization.has_value()) {
            return true;
        }

        if constexpr (PrettyErrors) {
            const auto error_message = std::string{display_string_of(^^Type)}
                + " does not define member function '"
                + detail::format_func_name(name, sig) + "'"
                + " and does not specialize rjk::impl";

            detail::display_error(error_message);
        }
        return false;
    }
}

enum struct op_overload_kind {
    any_kind,
    binary_lhs,
    binary_rhs,
    unary,
    variadic
};

namespace detail {

template <typename T>
struct init_tag{};

struct sig_info {
    op_overload_kind kind{};
    fn_qualifiers qualifiers{};
    std::meta::info after_remove_self{};
    std::meta::info erased_ptr_type{};
};

consteval sig_info analyze_op_sig(std::meta::info full_sig, std::meta::operators op) {
    const auto self_count = std::ranges::count(
        parameters_of(full_sig) | std::views::transform(std::meta::decay),
        ^^self);
    const bool member_style = (self_count == 0);

    const auto after_remove_self = member_style
        ? remove_fn_qualifiers(full_sig)
        : detail::remove_arg(full_sig, ^^self);
    const auto qualifiers = member_style
        ? qualifiers_of(full_sig)
        : qualifiers_of_target(full_sig, ^^self);

    const auto kind = std::invoke([&] {
        if (op == op_parentheses || op == op_square_brackets) {
           return op_overload_kind::variadic;
        }
        if (parameters_of(after_remove_self).size() == 0) {
            return op_overload_kind::unary;
        }
        if (member_style || remove_cvref(parameters_of(full_sig)[0]) == ^^self) {
            return op_overload_kind::binary_lhs;
        }
        return op_overload_kind::binary_rhs;
    });

    return {
        .kind = kind,
        .qualifiers = qualifiers,
        .after_remove_self = after_remove_self,
        .erased_ptr_type = static_cast<bool>(qualifiers & fn_qualifiers::is_const)
            ? ^^const void* : ^^void*
    };
}

consteval sig_info analyze_op_tag(std::meta::info op_tag) {
    return analyze_op_sig(template_arguments_of(op_tag)[1],
        extract<std::meta::operators>(template_arguments_of(op_tag)[0]));
}

consteval bool is_const_tag(std::meta::info tag) {
    if (tag == ^^copy_tag) {
        return true;
    } else if (template_of(tag) == ^^has_fn) {
        return static_cast<bool>(qualifiers_of(template_arguments_of(tag)[1]) & fn_qualifiers::is_const);
    } else if (template_of(tag) == ^^has_op) {
        auto qualifiers = analyze_op_tag(tag).qualifiers;
        return static_cast<bool>(qualifiers & fn_qualifiers::is_const);
    } else {
        return true;
    }
}

consteval std::meta::info make_rhs_signature(std::meta::info member) {
    auto self_t = ^^self;
    if (is_const(member)) {
        self_t = add_const(self_t);
    }
    if (is_rvalue_reference_qualified(member)) {
        self_t = add_rvalue_reference(self_t);
    } else {
        self_t = add_lvalue_reference(self_t);
    }

    const auto base_func_t = remove_fn_qualifiers(type_of(member));
    const auto with_self = append_arg(self_t, base_func_t);

    return dealias(substitute(^^has_op_meta, {
        std::meta::reflect_constant(operator_of(member)),
        reflect_constant(with_self)
    }));
}

consteval std::vector<std::meta::info> members_to_tags(std::meta::info trait) {
    trait = dealias(trait);

    const auto constness_filter = [trait](auto tag) {
        if (!is_const(trait)) {
            return true;
        }
        return is_const_tag(tag);
    };

    if (extract<bool>(substitute(^^is_policy, {trait}))) {
        return template_arguments_of(trait)
            | std::views::filter(constness_filter)
            | std::ranges::to<std::vector>();
    }
    if (extract<bool>(substitute(^^is_perf_option, {trait}))) {
        if (has_annotation(trait, ^^::rjk::trait)) {
            display_error(std::string{display_string_of(trait)} +
                " cannot use both [[=rjk::perf_options]] and [[=rjk::trait]].");
        }
        return {};
    }

    const auto using_like = extract<bool>(substitute(^^is_like, {trait}));

    const auto subject = using_like ? template_arguments_of(trait)[0] : trait;

    constexpr static auto ctx = std::meta::access_context::unprivileged();

    auto starting_list = using_like ? all_members_of(subject) : members_of(subject, ctx);
    auto trait_tags = starting_list
        | std::views::filter([=](auto member) {
            if (is_function(member) && !is_user_declared(member)) {
                return false;
            }
            if (is_function(member) && has_identifier(member)) {
                return true;
            }
            if (is_operator_function(member)) {
                return true;
            }
            if (!using_like) {
                display_error(std::string{"Trait '"} + display_string_of(trait)
                    + "' cannot hold non-member function '" + display_string_of(member) + "'");
            }
            return false;
        })
        | std::views::filter([=](auto member) {
            if (!using_like) {
                return true;
            }
            return std::invoke(extract<bool(*)(std::meta::info)>(
                template_arguments_of(trait)[1]), member);
        })
        | std::views::transform([](auto member) -> std::vector<std::meta::info> {
            if (is_operator_function(member)) {
                if (has_annotation(member, ^^right_side)) {
                    return {make_rhs_signature(member)};
                }

                const auto lhs_sig = dealias(substitute(^^has_op_meta, {
                    std::meta::reflect_constant(operator_of(member)),
                    reflect_constant(type_of(member))
                }));

                if (has_annotation(member, ^^both_sides)) {
                    return {lhs_sig, make_rhs_signature(member)};
                }

                return {lhs_sig};
            } else if (is_function(member)) {
                const fixed_string fixed_str{identifier_of(member)};
                return {dealias(substitute(^^has_fn_meta, {
                    std::meta::reflect_constant(fixed_str),
                    reflect_constant(type_of(member))}
                ))};
            } else {
                return {};
            }
        })
        | std::views::join
        | std::views::filter(constness_filter)
        | std::ranges::to<std::vector>();

    if (!using_like) {
        auto base_tags = bases_of(trait, ctx)
            | std::views::transform([trait](auto base) {
                const auto base_type = type_of(base);
                if (is_const(trait)) {
                    return add_const(base_type);
                }
                return base_type;
            })
            | std::views::transform(members_to_tags)
            | std::views::join;
        trait_tags.append_range(base_tags);
    }

    return trait_tags;
}

}

template <std::meta::operators Op, duck_tag... Tags>
consteval bool has_operator_tag(op_overload_kind kind = op_overload_kind::any_kind) {
    template for (constexpr auto tag : {^^Tags...}) {
        if constexpr ((tag != ^^copy_tag) && template_of(tag) == ^^has_op) {
            if constexpr ([:template_arguments_of(tag)[0]:] != Op) {
                continue;
            } else {
                if (kind == op_overload_kind::any_kind) {
                    return true;
                }

                constexpr static auto op_kind = detail::analyze_op_tag(tag).kind;

                if (kind == op_kind) {
                    return true;
                }
            }
        }
    }
    return false;
}

template <typename Type, std::meta::info Tag, bool PrettyErrors>
consteval bool satisfies_op_tag() {
    constexpr static auto tag_op = [: template_arguments_of(Tag)[0] :];

    constexpr static auto [op_kind, qualifiers, after_remove_self, _]
        = detail::analyze_op_tag(Tag);

    using obj_type = std::conditional_t<
        static_cast<bool>(qualifiers & detail::fn_qualifiers::is_const), const Type, Type>;
    using ref_type = std::conditional_t<
        static_cast<bool>(qualifiers & detail::fn_qualifiers::rvalue_ref), obj_type&&, obj_type&>;

    constexpr static auto sig_refl = template_arguments_of(Tag)[1];

    constexpr static fixed_string pretty_error{
        std::string{display_string_of(^^Type)}
            + " does not define '"
            + detail::format_func_name(std::string{"operator"} +
                symbol_of(tag_op), sig_refl) + "' as member"
            + " or free function"};

    [[maybe_unused]] constexpr static auto check_ret = [](auto ret) {
        return detail::is_return_compatible(ret,
            ^^Type, return_type_of(sig_refl), PrettyErrors);
    };

    // Special cases: operator() / operator[] can have more than two arguments
    if constexpr (tag_op == op_parentheses || tag_op == op_square_brackets) {
        constexpr static bool has_member = std::ranges::any_of(
            detail::all_members_of(^^Type),
            [](auto member) {
                return is_operator_function(member) &&
                    operator_of(member) == tag_op &&
                    detail::is_compatible_sig(member, sig_refl, ^^Type, PrettyErrors);
            }
        );
        if constexpr (PrettyErrors) {
            static_assert(has_member, pretty_error);
        }
        return has_member;
    }
    else if constexpr (op_kind == op_overload_kind::unary) {
        constexpr static bool has_unary = detail::check_unary_op<
            tag_op, is_noexcept(sig_refl), obj_type, ref_type, check_ret>();
        if constexpr (PrettyErrors) {
            static_assert(has_unary, pretty_error);
        }
        return has_unary;
    } else {
        constexpr static auto sig = remove_fn_qualifiers(after_remove_self);
        using ret  = [: return_type_of(sig) :];
        using arg1 = [: parameters_of(sig)[0] :];
        if constexpr (op_kind == op_overload_kind::binary_lhs) {
            constexpr static bool has_binary_lhs = detail::check_binary_op<
                tag_op, is_noexcept(sig_refl), obj_type, ref_type, arg1, arg1, check_ret
            >();

            if constexpr (PrettyErrors) {
                static_assert(has_binary_lhs, pretty_error);
            }
            return has_binary_lhs;
        } else {
            constexpr static bool has_binary_rhs = detail::check_binary_op<
                tag_op, is_noexcept(sig_refl), arg1, arg1, obj_type, ref_type, check_ret
            >();

            if constexpr (PrettyErrors) {
                static_assert(has_binary_rhs, std::invoke([] consteval {
                    std::string error{display_string_of(dealias(^^arg1))};
                    error += " does not define '";

                    const auto dummy_func = detail::make_func(dealias(^^ret), {dealias(^^ref_type)});
                    const auto identifier = std::string{"operator"} + symbol_of(tag_op);
                    error += detail::format_func_name(identifier, dummy_func);
                    error += "' as member or free function";
                    return error;
                }));
            }
            return has_binary_rhs;
        }
    }
}
template <typename Type, typename RelevantTrait, bool PrettyErrors, typename... Tags>
consteval bool satisfies_tags() {
    if constexpr (has_template_arguments(^^Type) && (
        template_of(^^Type) == ^^std::in_place_type_t ||
        template_of(^^Type) == ^^detail::init_tag ||
        template_of(^^Type) == ^^duck ||
        template_of(^^Type) == ^^duck_view)) {
        return false; // Avoids static assertion triggering during subsumption
    } else {
        template for (constexpr auto tag : {^^Tags...}) {
            if constexpr (tag == ^^copy_tag) {
                if constexpr (std::copyable<Type>) {
                    continue;
                } else {
                    if constexpr (PrettyErrors) {
                        static_assert(false, std::string{display_string_of(^^Type)}
                            + " is not copyable");
                    }
                }
            }
            else if constexpr (template_of(tag) == ^^has_fn) {
                if (satisfies_fn_tag<Type, RelevantTrait, tag, PrettyErrors>()) {
                    continue;
                }
            }
            else if constexpr (template_of(tag) == ^^has_op) {
                if constexpr (satisfies_op_tag<Type, tag, PrettyErrors>()) {
                    continue;
                }
            }
            return false;
        }
        return true;
    }
}

// Explicit Trait1 to prevent using satisfies for zero traits
template <typename T, typename Trait1, typename... Traits>
concept satisfies = is_trait<Trait1> && (is_trait<Traits> && ...) && std::invoke([] consteval {
    const std::array traits{^^Trait1, ^^Traits...};
    return std::ranges::all_of(traits, [](auto trait) {
        const auto satisfy_func = substitute(^^satisfies_tags,
            std::views::concat(
                std::array{^^T, trait, std::meta::reflect_constant(false)},
                detail::members_to_tags(trait)
            ));
        return std::invoke(extract<bool(*)()>(satisfy_func));
    });
});

consteval std::string op_tag_to_string(std::meta::info tag) {
    const auto [op_kind, _, after_remove_self, _]
        = detail::analyze_op_tag(tag);

    const auto kind_identifier = std::invoke([&] -> std::string_view {
        switch (op_kind) {
            using enum op_overload_kind;
        case variadic:
            return "";
        case unary:
            return "unary_";
        case binary_lhs:
            return "lhs_";
        case binary_rhs:
            return "rhs_";
        default:
            return "";
        }
    });

    return std::string{"_rjk__"} + kind_identifier
        + enum_to_string(extract<std::meta::operators>(template_arguments_of(tag)[0]));
}

consteval fixed_string op_tag_to_fixed_string(std::meta::info tag) {
    return fixed_string{std::string_view{op_tag_to_string(tag)}};
}
}

#endif
/*** End of inlined file: duck_tags.hpp ***/

namespace rjk::detail {

// Return deduction implementation for duck.
template <typename TraitRet, typename ActualRet>
constexpr TraitRet convert_duck_return(ActualRet&& result)
noexcept(is_conversion_noexcept_impl<TraitRet, ActualRet>()) {
    if constexpr (std::same_as<TraitRet, ActualRet>) {
        return std::forward<ActualRet>(result);
    } else if constexpr (is_pointer_type(^^ActualRet)) {
        if (result == nullptr) {
            return TraitRet{};
        }
        return TraitRet{*result};
    } else {
        return TraitRet{std::forward<ActualRet>(result)};
    }
}

template <typename Sig, fn_qualifiers Qualifiers, std::meta::info TMember, typename T, bool FunctionCallSyntax>
struct vtable_fn_maker;

template <typename Ret, typename... Args, bool Noexcept,
    fn_qualifiers Qualifiers, std::meta::info TMember, typename T, bool FunctionCallSyntax>
struct vtable_fn_maker<Ret(Args...) noexcept(Noexcept), Qualifiers, TMember, T, FunctionCallSyntax> {
    constexpr static auto refl_erased_ptr_type =
        static_cast<bool>(Qualifiers & fn_qualifiers::is_const)
        ? ^^const void* : ^^void*;
    using erased_ptr_type = [:refl_erased_ptr_type:];

    using function_ptr = Ret(*)(erased_ptr_type, Args...) noexcept(Noexcept);

    constexpr static Ret erased_call(erased_ptr_type context, Args... args) noexcept(Noexcept) {
        using obj_type = std::conditional_t<
                static_cast<bool>(Qualifiers & fn_qualifiers::is_const), const T, T>;
        using ref_type = std::conditional_t<
            static_cast<bool>(Qualifiers & fn_qualifiers::rvalue_ref), obj_type&&, obj_type&>;

        // We have to branch here so a void type doesn't get forwarded to
        // convert_duck_return.
        if constexpr (std::same_as<Ret, void>) {
            if constexpr (FunctionCallSyntax) {
                return [:TMember:](
                    static_cast<ref_type>(*static_cast<obj_type*>(context)),
                    std::forward<Args>(args)...
                );
            } else {
                return static_cast<ref_type>(*static_cast<obj_type*>(context))
                    .[:TMember:](std::forward<Args>(args)...);
            }
        } else {
            if constexpr (FunctionCallSyntax) {
                decltype(auto) result = [:TMember:](
                    static_cast<ref_type>(*static_cast<obj_type*>(context)),
                    std::forward<Args>(args)...
                );
                return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
            } else {
                decltype(auto) result = static_cast<ref_type>(*static_cast<obj_type*>(context))
                    .[:TMember:](std::forward<Args>(args)...);
                return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
            }
        }
    }

    consteval static function_ptr make() {
        return &erased_call;
    }
};

template <typename Sig, fn_qualifiers Qualifiers, std::meta::operators Op,
    op_overload_kind Kind, typename T>
struct vtable_op_maker;

template <typename Ret, typename... Args, bool Noexcept, fn_qualifiers Qualifiers, std::meta::operators Op,
    op_overload_kind Kind, typename T>
struct vtable_op_maker<Ret(Args...) noexcept(Noexcept), Qualifiers, Op, Kind, T> {
    constexpr static auto refl_erased_ptr_type =
        static_cast<bool>(Qualifiers & fn_qualifiers::is_const)
        ? ^^const void* : ^^void*;
    using erased_ptr_type = [:refl_erased_ptr_type:];

    using function_ptr = Ret(*)(erased_ptr_type, Args...) noexcept(Noexcept);

    constexpr static Ret erased_call(erased_ptr_type context, Args... args) noexcept(Noexcept) {
        using obj_type = std::conditional_t<
            static_cast<bool>(Qualifiers & fn_qualifiers::is_const), const T, T>;
        using ref_type = std::conditional_t<
            static_cast<bool>(Qualifiers & fn_qualifiers::rvalue_ref), obj_type&&, obj_type&>;

        auto* typed = static_cast<obj_type*>(context);

        if constexpr (Op == op_parentheses) {
            if constexpr (std::same_as<Ret, void>) {
                static_cast<ref_type>(*typed)
                    .operator()(std::forward<Args>(args)...);
                return;
            } else {
                decltype(auto) result = static_cast<ref_type>(*typed)
                    .operator()(std::forward<Args>(args)...);
                return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
            }
        } else if constexpr (Op == op_square_brackets) {
            if constexpr (std::same_as<Ret, void>) {
                static_cast<ref_type>(*typed)
                    .operator[](std::forward<Args>(args)...);
                return;
            } else {
                decltype(auto) result = static_cast<ref_type>(*typed)
                    .operator[](std::forward<Args>(args)...);
                return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
            }
        } else if constexpr (Kind == op_overload_kind::unary) {
            if constexpr (std::same_as<Ret, void>) {
                do_unary_op<Op, Noexcept>(static_cast<ref_type>(*typed));
                return;
            } else {
                decltype(auto) result =
                    do_unary_op<Op, Noexcept>(static_cast<ref_type>(*typed));
                return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
            }
        } else {
            if constexpr (Kind == op_overload_kind::binary_lhs) {
                if constexpr (std::same_as<Ret, void>) {
                    do_binary_op<Op, Noexcept>(static_cast<ref_type>(*typed),
                        std::forward<Args...[0]>(args...[0]));
                    return;
                } else {
                    decltype(auto) result =
                        do_binary_op<Op, Noexcept>(static_cast<ref_type>(*typed),
                        std::forward<Args...[0]>(args...[0]));
                    return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
                }
            }
            else {
                if constexpr (std::same_as<Ret, void>) {
                    do_binary_op<Op, Noexcept>(std::forward<Args...[0]>(args...[0]),
                        static_cast<ref_type>(*typed));
                    return;
                } else {
                    decltype(auto) result =
                        do_binary_op<Op, Noexcept>(std::forward<Args...[0]>(args...[0]),
                        static_cast<ref_type>(*typed));
                    return convert_duck_return<Ret>(std::forward<decltype(result)>(result));
                }
            }
        }
    }

    consteval static function_ptr make() noexcept {
        return &erased_call;
    }
};

// TODO: Remove once GCC fixes bug
template <std::meta::info Sig, fn_qualifiers Qualifiers, std::meta::operators Op,
    op_overload_kind Kind, std::meta::info T>
using vtable_op_maker_meta = vtable_op_maker<typename [:Sig:], Qualifiers, Op, Kind, typename [:T:]>;

// TODO: Remove once GCC fixes bug
template <std::meta::info Sig, fn_qualifiers Qualifiers, std::meta::info TMember, std::meta::info T>
using vtable_fn_maker_meta = vtable_fn_maker<
    typename [:Sig:], Qualifiers, TMember, typename [:T:], false>;

// TODO: Remove once GCC fixes bug
template <std::meta::info Sig, fn_qualifiers Qualifiers, std::meta::info TMember, std::meta::info T>
using vtable_fn_maker_for_impl_meta = vtable_fn_maker<
    typename [:Sig:], Qualifiers, TMember, typename [:T:], true>;
}

#endif

/*** End of inlined file: vtable_fn_maker.hpp ***/

namespace rjk::detail {

template <typename DuckVtableGenerator>
class storage;

consteval std::string index_to_string(std::size_t index) {
    if (index == 0UZ) return std::string{'0'};
    std::string digits{};
    while (index > 0UZ) {
        digits += ('0' + index % 10UZ);

        index /= 10UZ;
    }
    std::ranges::reverse(digits);
    return digits;
}

consteval std::string index_to_slot_name(std::size_t index) {
    return "slot_" + index_to_string(index);
}

consteval std::string index_to_trait_name(std::size_t index) {
    return "to_trait_" + index_to_string(index);
}

template <is_trait... Traits>
struct vtable_generator {
    constexpr static auto ctx = std::meta::access_context::unprivileged();

    constexpr static std::array<std::meta::info, sizeof...(Traits)>
        traits{^^Traits...};

    constexpr static auto tags = define_static_array(traits
        | std::views::transform(members_to_tags)
        | std::views::join);

    constexpr static auto can_copy = std::ranges::contains(tags, ^^copy_tag);
    constexpr static auto is_mutable = (!std::is_const_v<Traits> || ...);

    using StorageType = storage<vtable_generator>;

    struct vtable;

    consteval {
        std::vector<std::meta::info> members{
            data_member_spec(^^void(*)(StorageType&) noexcept, {.name = "destroy"}),
            data_member_spec(^^void(*)(void*, StorageType&) noexcept, {.name = "move"})
        };
        if constexpr (can_copy) {
            members.push_back(data_member_spec(^^void(*)(const void*, StorageType&), {.name = "copy"}));
        }
        if constexpr (is_mutable) {
            members.push_back(data_member_spec(
                ^^const typename vtable_generator<const Traits...>::vtable*,
                {.name = "to_const"}
            ));
        }

        [[maybe_unused]] std::size_t index{};
        template for (constexpr auto trait_index : std::views::indices(traits.size())) {
            constexpr static auto trait = traits[trait_index];
            constexpr static auto trait_table = substitute(
                ^^::rjk::detail::vtable_generator, {trait});

            members.push_back(data_member_spec(
                ^^const typename [:trait_table:]::vtable*,
                {.name = index_to_trait_name(trait_index)}
            ));

            for (const auto tag : members_to_tags(trait)) {
                if (tag == ^^copy_tag) {
                    index++;
                    continue;
                }

                const auto full_sig = template_arguments_of(tag)[1];
                if (template_of(tag) == ^^has_fn) {
                    const auto erased_ptr_type =
                        analyze_op_sig(template_arguments_of(tag)[1], op_parentheses)
                        .erased_ptr_type;

                    const auto sig = remove_fn_qualifiers(full_sig);
                    const auto ptr_type = add_pointer(prepend_arg(
                        erased_ptr_type, sig));
                    members.push_back(data_member_spec(ptr_type, {
                        .name = index_to_slot_name(index)
                    }));
                }
                else if (template_of(tag) == ^^has_op) {
                    const auto [_, qualifiers, after_remove_self,
                        erased_ptr_type] = analyze_op_tag(tag);

                    const auto sig = remove_fn_qualifiers(after_remove_self);
                    const auto ptr_type = add_pointer(prepend_arg(
                        erased_ptr_type, sig));
                    members.push_back(data_member_spec(ptr_type, {
                        .name = index_to_slot_name(index)
                    }));
                }

                index++;
            }
        }

        define_aggregate(^^vtable, members);
    }

    constexpr static auto vtable_members = define_static_array(
        nonstatic_data_members_of(^^vtable, ctx));

    consteval static auto find_trait(std::meta::info trait) {
        struct ret_value {
            const std::meta::info* trait_loc;
            bool should_constify;
        };
        if (const auto with_const = std::ranges::find(traits, trait);
                    with_const != traits.end()) {
            return ret_value{with_const, false};
                    }
        if (const auto without_const =
                std::ranges::find(traits, remove_const(trait));
                without_const != traits.end()) {
            return ret_value{without_const, true};
                }
        display_error("trait not found");
    }

    template <is_trait Trait> requires
        ((std::same_as<Traits, Trait> || ...) ||
        (std::same_as<Traits, std::remove_const_t<Trait>> || ...))
    constexpr static const vtable_generator<Trait>::vtable* convert(const vtable* table) {
        constexpr static auto trait_info = find_trait(^^Trait);

        constexpr static auto member = *std::ranges::find_if(
            vtable_members,
            [](auto member) {
                return identifier_of(member) == index_to_trait_name(
                    std::ranges::distance(traits.begin(), trait_info.trait_loc));
            }
        );

        if constexpr (trait_info.should_constify) {
            return table->[:member:]->to_const;
        } else {
            return table->[:member:];
        }
    }

    consteval static std::meta::info find_trait_for_tag(std::meta::info tag) {
        return *std::ranges::find_if(traits, [tag](auto trait) {
            return std::ranges::contains(members_to_tags(trait), tag);
        });
    }

    // The special functions, like move, copy, and destroy, are defined in
    // detail/storage.hpp.
    template <typename T>
    consteval static void set_storage_functions(vtable& static_vtable);

    template <typename T>
    consteval static vtable make_vtable();

    // Generates a static_vtable with the correct member functions for T.
    template <typename T>
    constexpr static auto static_vtable_for = make_vtable<T>();
};

// TODO: Remove once GCC fixes bug
template <std::meta::info... Traits>
using vtable_generator_meta = vtable_generator<typename [:Traits:]...>;

template <is_trait... Traits>
template <typename T>
consteval auto vtable_generator<Traits...>::make_vtable() -> vtable {
    vtable table{};
    if constexpr (is_mutable) {
        table.to_const = &vtable_generator<const Traits...>::template
            static_vtable_for<T>;
    }
    set_storage_functions<T>(table);

    template for (constexpr auto index : std::views::indices(traits.size())) {
        constexpr static auto converter = *std::ranges::find_if(
            vtable_members,
            [](auto member) { return identifier_of(member) == index_to_trait_name(index); }
        );
        table.[:converter:] = &vtable_generator<Traits...[index]>::template
            static_vtable_for<T>;
    }

    template for (constexpr auto index : std::views::indices(tags.size())) {
        constexpr static auto tag = tags[index];

        if constexpr (tag != ^^copy_tag) {
            constexpr static auto slot = *std::ranges::find_if(
                vtable_members,
                [](auto member) { return identifier_of(member) == index_to_slot_name(index); }
            );

            if constexpr (has_template_arguments(tag) && template_of(tag) == ^^has_fn) {
                constexpr static auto member_name = template_arguments_of(tag)[0];
                constexpr static auto full_sig    = template_arguments_of(tag)[1];
                constexpr static auto qualifiers  = qualifiers_of(full_sig);

                constexpr static auto T_member = std::invoke([] consteval
                    -> std::optional<std::meta::info> {
                    for (const auto m : detail::all_members_of(^^T)) {
                        if (has_identifier(m) && is_function(m) &&
                            identifier_of(m) == std::string_view{[:member_name:]} &&
                            is_compatible_sig(m, full_sig, ^^T, true)
                        ) {
                            return m;
                        }
                    }
                    return std::nullopt;
                });

                constexpr static auto sig = remove_fn_qualifiers(full_sig);

                constexpr static auto fn_maker = std::invoke([] {
                    if constexpr (T_member.has_value()) {
                        const auto member = T_member.value();
                        return substitute(^^vtable_fn_maker_meta, {
                            reflect_constant(sig),
                            std::meta::reflect_constant(qualifiers),
                            reflect_constant(member),
                            reflect_constant(^^T)
                        });
                    } else {
                        const auto member = *find_impl_specialization(^^T, find_trait_for_tag(tag),
                            std::string_view{[:member_name:]}, full_sig, true);

                        return substitute(^^vtable_fn_maker_for_impl_meta, {
                            reflect_constant(sig),
                            std::meta::reflect_constant(qualifiers),
                            reflect_constant(member),
                            reflect_constant(^^T)
                        });
                    }
                });

                table.[:slot:] = [:fn_maker:]::make();
            }
            else if constexpr (has_template_arguments(tag) && template_of(tag) == ^^has_op) {
                constexpr static auto [op_kind, qualifiers, after_remove_self, _]
                    = analyze_op_tag(tag);
                constexpr static auto tag_op = template_arguments_of(tag)[0];

                constexpr static auto sig = remove_fn_qualifiers(after_remove_self);

                constexpr static auto op_maker = substitute(^^vtable_op_maker_meta, {
                    reflect_constant(sig),
                    std::meta::reflect_constant(qualifiers),
                    tag_op,
                    std::meta::reflect_constant(op_kind),
                    reflect_constant(^^T)
                });

                table.[:slot:] = [:op_maker:]::make();
            }
        }
    }

    return table;
}

}

#endif

/*** End of inlined file: vtable_generator.hpp ***/

namespace rjk::detail {

consteval static bool is_duck_view(std::meta::info type) {
    return has_template_arguments(type)
        && is_type(type)
        && template_of(type) == ^^duck_view;
}

// Provides some helper functions for determining if a duck type subsumes another
// duck type.
template <is_trait... Traits>
struct subsumption_utils {
    constexpr static std::array<std::meta::info, sizeof...(Traits)>
        traits{^^Traits...};

    consteval static bool total_subsumption(std::meta::info type) {
        if (!is_duck_type(type)) {
            return false;
        }

        const auto args = template_arguments_of(type);
        if (sizeof...(Traits) == 1 && args.size() != 1) {
            return false;
        }
        return std::ranges::equal(traits, args);
    }

    consteval static bool total_const_subsumption(std::meta::info type) {
        if (sizeof...(Traits) == 1) {
            return false;
        }
        if (!is_duck_type(type)) {
            return false;
        }

        const auto args = template_arguments_of(type);

        if (std::ranges::all_of(args, std::meta::is_const)) {
            return false;
        }

        return std::ranges::equal(traits,
            args | std::views::transform(std::meta::add_const)
        );
    }

    consteval static bool single_trait_subsumption(std::meta::info type) {
        if (!is_duck_type(type)) {
            return false;
        }
        if (total_subsumption(type)) {
            return false;
        }
        if (sizeof...(Traits) != 1) {
            return false;
        }

        const auto args = template_arguments_of(type);
        return std::ranges::contains(
            args | std::views::transform(std::meta::remove_const),
            remove_const(*traits.begin())
        );
    }

    template <typename Duck>
    constexpr static const vtable_generator<Traits...>::vtable* convert_from(const auto* table) {
        constexpr static auto duck_t = decay(^^Duck);
        constexpr static auto gen_t = substitute(^^vtable_generator,
            template_arguments_of(duck_t));
        return [:gen_t:]::template convert<Traits...[0]>(table);
    }
};
}

#endif

/*** End of inlined file: subsumption_utils.hpp ***/


namespace rjk {

template <is_trait... Traits>
class duck_ptr;

template <is_trait... Traits>
class duck_view
    : public detail::duck_behavior_base<duck_view<Traits...>, Traits...> {
private:
    using duck_base_t = detail::make_duck_base_t<duck_view, Traits...>;

    constexpr static bool all_const = sizeof...(Traits) > 0 && (std::is_const_v<Traits> && ...);

    using underlying_ptr_t = std::conditional_t<all_const, const void*, void*>;

    using util = detail::subsumption_utils<Traits...>;
public:
    template <typename T> requires
        (!detail::is_duck_type(^^T) &&
        duck_base_t::template meets_tags<T>())
    constexpr duck_view(T&& obj) noexcept
        : m_underlying(std::addressof(obj))
        , m_vtable(&duck_base_t::template static_vtable_for<std::decay_t<T>>) {
        static_assert(all_const || !std::is_const_v<std::remove_reference_t<T>>,
            "Cannot bind duck_view with mutable traits to a const object");
    }

    template <typename Duck>
    constexpr duck_view(Duck&& d) noexcept requires (
        !std::same_as<std::decay_t<Duck>, duck_view> &&
        util::total_subsumption(decay(^^Duck))
    )
        : m_underlying(d.get_underlying())
        , m_vtable(d.get_vtable())
    { }

    template <typename Duck> requires (util::total_const_subsumption(decay(^^Duck)))
    constexpr duck_view(Duck&& d) noexcept
        : m_underlying(d.get_underlying())
        , m_vtable(d.get_vtable()->to_const)
    { }

    template <typename Duck> requires (util::single_trait_subsumption(decay(^^Duck)))
    constexpr duck_view(Duck&& d) noexcept
        : m_underlying(d.get_underlying())
        , m_vtable(util::template convert_from<Duck>(d.get_vtable()))
    { }

    template <std::meta::info VtableMember, duck_tag Tag, detail::fn_qualifiers Qualifiers, typename Func>
    friend class duck_base_t::vtable_function;

    template <typename Derived, is_trait... BaseTraits>
    friend class detail::duck_behavior_base;

    template <is_trait... ViewTraits>
    friend class duck_view;

    template <is_trait... DuckTraits>
    friend class duck;

    friend class duck_ptr<Traits...>;
private:
    constexpr duck_view() noexcept : m_underlying(nullptr), m_vtable(nullptr) { }

    template <typename T>
    constexpr bool has_type() const noexcept { return m_vtable == &duck_base_t::template static_vtable_for<T>; }

    constexpr const auto* get_vtable() const noexcept { return m_vtable; }

    constexpr underlying_ptr_t get_underlying() const noexcept { return m_underlying; }
private:
    underlying_ptr_t m_underlying;
    const duck_base_t::vtable* m_vtable;
};

template <is_trait... Traits>
duck_view(duck<Traits...>&) -> duck_view<Traits...>;

template <is_trait... Traits>
duck_view(duck<Traits...>&&) -> duck_view<Traits...>;

template <is_trait... Traits>
duck_view(const duck<Traits...>&) -> duck_view<const Traits...>;

template <typename T, is_trait... Traits> requires
    (!std::same_as<std::decay_t<T>, duck<Traits...>> &&
    !std::same_as<std::decay_t<T>, duck_view<Traits...>>)
duck_view(T&&) -> duck_view<>;

template <is_trait... Traits>
class duck_ptr {
private:
    using duck_base_t = duck_view<Traits...>::duck_base_t;
    using util = detail::subsumption_utils<Traits...>;
public:
    constexpr duck_ptr() noexcept = default;
    constexpr duck_ptr(std::nullopt_t) noexcept {}

    constexpr duck_ptr(duck_view<Traits...> view) noexcept : m_view(view) {}

    template <typename T>
    constexpr duck_ptr(T&& obj) noexcept : m_view(std::forward<T>(obj)) {}

    constexpr bool has_value() const noexcept {
        return m_view.get_underlying() != nullptr;
    }

    constexpr explicit operator bool() const noexcept {
        return has_value();
    }

    constexpr duck_view<Traits...> value() const {
#ifdef __EXCEPTIONS
        if (!has_value()) {
            throw bad_duck_access{"duck_ptr is empty"};
        }
#else
        assert(has_value() && "duck_ptr is empty");
#endif

        return m_view;
    }

    constexpr duck_view<Traits...> operator*() const noexcept {
        assert(has_value());
        return m_view;
    }

    constexpr duck_view<Traits...>* operator->() noexcept {
        assert(has_value());
        return &m_view;
    }

    constexpr const duck_view<Traits...>* operator->() const noexcept {
        assert(has_value());
        return &m_view;
    }
private:
    duck_view<Traits...> m_view;
};

template <is_trait... Traits>
duck_ptr(duck<Traits...>&) -> duck_ptr<Traits...>;

template <is_trait... Traits>
duck_ptr(duck<Traits...>&&) -> duck_ptr<Traits...>;

template <is_trait... Traits>
duck_ptr(const duck<Traits...>&) -> duck_ptr<const Traits...>;

template <is_trait... Traits>
duck_ptr(duck_view<Traits...>) -> duck_ptr<Traits...>;
}

#endif

