import argparse
import sys
from enum import Flag

class Overloads(Flag):
    UNARY = 1
    BINARY = 1 << 1
    BOTH = UNARY | BINARY

OPERATORS = [
    # --- Unary Only Operators ---
    ('op_tilde', '~', Overloads.UNARY),
    ('op_exclamation', '!', Overloads.UNARY),
    ('op_plus_plus', '++', Overloads.UNARY), # Post-fix is defined separately
    ('op_minus_minus', '--', Overloads.UNARY), # Post-fix is defined separately

    # Both Unary and Binary Operators
    ('op_plus', '+', Overloads.BOTH),
    ('op_minus', '-', Overloads.BOTH),
    ('op_star', '*', Overloads.BOTH),       # Unary dereference & Binary multiply
    ('op_ampersand', '&', Overloads.BOTH),  # Unary address-of & Binary bitwise AND

    # Binary Only Operators
    ('op_slash', '/', Overloads.BINARY),
    ('op_percent', '%', Overloads.BINARY),
    ('op_caret', '^', Overloads.BINARY),
    ('op_pipe', '|', Overloads.BINARY),
    ('op_less_less', '<<', Overloads.BINARY),
    ('op_greater_greater', '>>', Overloads.BINARY),
    ('op_comma', ',', Overloads.BINARY),

    # Assignment Operators
    ('op_plus_equals', '+=', Overloads.BINARY),
    ('op_minus_equals', '-=', Overloads.BINARY),
    ('op_star_equals', '*=', Overloads.BINARY),
    ('op_slash_equals', '/=', Overloads.BINARY),
    ('op_percent_equals', '%=', Overloads.BINARY),
    ('op_caret_equals', '^=', Overloads.BINARY),
    ('op_ampersand_equals', '&=', Overloads.BINARY),
    ('op_pipe_equals', '|=', Overloads.BINARY),
    ('op_less_less_equals', '<<=', Overloads.BINARY),
    ('op_greater_greater_equals', '>>=', Overloads.BINARY),

    # Comparison Operators
    ('op_equals_equals', '==', Overloads.BINARY),
    ('op_exclamation_equals', '!=', Overloads.BINARY),
    ('op_less', '<', Overloads.BINARY),
    ('op_greater', '>', Overloads.BINARY),
    ('op_less_equals', '<=', Overloads.BINARY),
    ('op_greater_equals', '>=', Overloads.BINARY),
    ('op_spaceship', '<=>', Overloads.BINARY),

    # Logical Operators
    ('op_ampersand_ampersand', '&&', Overloads.BINARY),
    ('op_pipe_pipe', '||', Overloads.BINARY),
]

def generate_header(include_guard, template, function_name, args):
    return [
        "// This file was automatically generated by generate_operators.py.",
        "",
        f"#ifndef {include_guard}",
        f"#define {include_guard}",
        "",
        "#include <meta>",
        "",
        "namespace rjk {",
        "",
        template,
        f"constexpr decltype(auto) {function_name}({args}) {{",
        "using enum std::meta::operators;"
    ]

def generate_footer():
    return [
        "    throw std::logic_error{\"invalid operator\"};"
        "}",
        "}",
        "",
        "#endif"
    ]

def generate_unary():
    lines = generate_header(
        "RJK_DO_UNARY_OP_HPP",
        "template <std::meta::operators Op, typename Operand>",
        "do_unary_op",
        "Operand&& operand"
    )

    for enum_id, symbol, overload in OPERATORS:
        if not Overloads.UNARY in overload:
            continue

        lines.append(f"    if constexpr (Op == {enum_id}) return {symbol}std::forward<Operand>(operand);")

    lines.extend(generate_footer())
    return "\n".join(lines)

def generate_binary():
    lines = generate_header(
        "RJK_DO_BINARY_OP_HPP",
        "template <std::meta::operators Op, typename Lhs, typename Rhs>",
        "do_binary_op",
        "Lhs&& lhs, Rhs&& rhs"
    )

    for enum_id, symbol, overload in OPERATORS:
        if not Overloads.BINARY in overload:
            continue

        lines.append(f"    if constexpr (Op == {enum_id}) return std::forward<Lhs>(lhs) {symbol} std::forward<Rhs>(rhs);")

    # Script would break if we added these normally, since it would try lhs ++ rhs
    lines.append(f"    if constexpr(Op == op_plus_plus) return std::forward<Lhs>(lhs)++;")
    lines.append(f"    if constexpr(Op == op_minus_minus) return std::forward<Lhs>(lhs)--;")

    lines.extend(generate_footer())
    return "\n".join(lines)

def generate_friends():
    lines = [
        "// This file was automatically generated by generate_operators.py.",
        ""
    ]

    for enum_id, symbol, overload in OPERATORS:
        lines.append(f"// {f' {enum_id} ':-^90}")
        lines.append("")
        if Overloads.UNARY in overload:
            lines.extend([
                "template <typename This> ",
                f"requires (satisfies_operator<{enum_id}, This, void>(op_overload_kind::unary))",
                f"friend decltype(auto) operator{symbol}(This&& operand) {{",
                f"    return std::forward<This>(operand)._rjk__unary_{enum_id}();",
                "}",
                ""
            ])
        if Overloads.BINARY in overload:
            lines.extend([
                "template <typename This, typename R>",
                f"requires (satisfies_operator<{enum_id}, This, R>(op_overload_kind::binary_lhs))",
                f"friend decltype(auto) operator{symbol}(This&& lhs, R&& rhs) {{",
                f"    return std::forward<This>(lhs)._rjk__lhs_{enum_id}(std::forward<R>(rhs));",
                "}",
                ""
            ])
            lines.extend([
                "template <typename L, typename This>",
                f"requires (satisfies_operator<{enum_id}, L, This>(op_overload_kind::binary_rhs))",
                f"friend decltype(auto) operator{symbol}(L&& lhs, This&& rhs) {{",
                f"    return std::forward<This>(rhs)._rjk__rhs_{enum_id}(std::forward<L>(lhs));",
                "}",
                ""
            ])

    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(
        description="Generates operator boilerplate for rjk::duck.",
        usage="python generate_operators.py [--unary <path>] [--binary <path>] [--friends <path>]"
    )

    parser.add_argument("--unary", metavar="output_path", help="Path for unary operators")
    parser.add_argument("--binary", metavar="output_path", help="Path for binary operators")
    parser.add_argument("--friends", metavar="output_path", help="Path for friend operators")

    args = parser.parse_args()

    if not (args.unary or args.binary or args.friends):
        parser.error("Specify one or more of: --unary, --binary, --friends")

    generation_tasks = [
        (args.unary, generate_unary),
        (args.binary, generate_binary),
        (args.friends, generate_friends)
    ]

    for output_file, generator_func in generation_tasks:
        if not output_file:
            continue

        print()
        print(f"Writing to {output_file}...")
        with open(output_file, "w") as file:
            file.write(generator_func())
        print(f"Successfully generated {output_file}.")

if __name__ == "__main__":
    main()